---
-  name: Playbook to setup httpd
   hosts: localhost
   become: true

   tasks:
   - name: install httpd
     ansible.builtin.package:
       name: httpd
       state: latest
   - name: copy index.html
     ansible.builtin.copy:
      src: index.html
      dest: /var/www.html
      mode: 0644
      owner: root
      group: root
   - name: start https server
     ansible.builtin.service:
       name: httpd
       state: started
